### ISSUE TITLE
CLColorConvert and NEColorConvert output does not match for some input-output combinations

### ISSUE THREAD

**Issue by rohit-unnimadhavan** [ARM-software/ComputeLibrary#321]
Hi,

The outputs for NEColorConvert and CLColorConvert do not match when trying to convert a YUV image to RGB space. This is observed for conversions from UYVY422/YUYV422/IYUV/NV12/NV21 to RGB888/RGBA888. 

A sample code illustrating the mismatch for conversion from UYVY422 image to RGB888 is attached here. From the log, it can be seen that some bytes are 255 in NEON while the corresponding CL output is some other number. Similar mismatch happens for other combinations also.

Is this a known issue? Is there a overflow handling parameter for these classes? Kindly help to resolve this.

Thanks,
Rohit

[acl_colorconvert.txt](https://github.com/ARM-software/ComputeLibrary/files/1587444/acl_colorconvert.txt)
[colorConvert_CL_and_NEON_mismatch.txt](https://github.com/ARM-software/ComputeLibrary/files/1587445/colorConvert_CL_and_NEON_mismatch.txt)

**Comment by rohit-unnimadhavan** [comment]
RGB888->RGBA8888  and RGBA8888->RGB888 conversions seem to be proper on both CL and NEON.

**Comment by rohit-unnimadhavan** [comment]
Facing the following issues also in ColorConvert kernels on NEON and CL.

2. RGB888 => YUV444 :
For some input pixels, output chroma pixels from NEON and CL mismatches. 

- For example, for R= 33, G = 81, B = 46, output pixels are Y = 68, U = 115, V = 105 on NEON but Y = 68, U = 117, V = 106 on CL. Note that there is a difference of 2 in U data. 
- Another example: R = 37, G = 126, B = 246 gives Y = 115, U = 198, V = 77 on NEON and Y = 115, U = 198, V = 79 on CL, a difference of 2 in V data.

In both above examples, CL seems to be giving the proper pixels. Could you please look into this and confirm whether there's an issue on NEON (or CL) side?

3. RGBA8888 => YUV444 on NEON:
Here also, on NEON side there is a difference of 2 in U/V data.

4. RGBA8888 => YUV444 on CL:
Here, unlike RGB888 => YUV444 CL output is not at all proper. I am attaching both CL and NEON outputs here for different resolutions. While there is a difference of +/-2 from the expected output on NEON side (No.3 above), certain pixels in CL side differs from the expected output by a large margin.

Request to look into these also and resolve the concerns.

Thanks,
Rohit

Log files:
[colorConvert_CL_and_NEON_RGB_to_YUV4_mismatch_8x8.txt](https://github.com/ARM-software/ComputeLibrary/files/1589028/colorConvert_CL_and_NEON_RGB_to_YUV4_mismatch_8x8.txt)
[colorConvert_CL_and_NEON_RGBA_to_YUV4_issue_8x8.txt](https://github.com/ARM-software/ComputeLibrary/files/1589029/colorConvert_CL_and_NEON_RGBA_to_YUV4_issue_8x8.txt)
[colorConvert_CL_and_NEON_RGBA_to_YUV4_issue_16x8.txt](https://github.com/ARM-software/ComputeLibrary/files/1589030/colorConvert_CL_and_NEON_RGBA_to_YUV4_issue_16x8.txt)

**Comment by cristian-szabo-arm** [comment]
Hi Rohit,

I've run the code provided on different devices with different configurations and I was not able to reproduce the issue.

In order to help you further with this issue, can you please provide the Scons build parameters and the device (OS, Arch) you are using to test? Also, are you using the latest ACL version (17.12)? If you are running on an Android device, can you provide the NDK revision you've used?

Kind regards,
Chris

**Comment by rohit-unnimadhavan** [comment]
Hi Chris,

We are not using Scons to build the compute library. We are using a proprietary tool chain to build the compute library on an Ubuntu machine. We are using ACL version 17.10 currently. Are there any fixes for color convert kernels in 17.12? We are also not running on Android device but a Linux device. We can't share more details about the device as of now.

Please let me know if you need more information from our side.

Thanks,
Rohit

**Comment by AnthonyARM** [comment]
Hi Rohit,

Yes, there's been several bug fixes in v17.12 so it's worth of a try.
If this doesn't solve your problem I'm afraid there isn't much more we can do to help if we can't reproduce the error on our side with the recommended toolchains.

**Comment by GeorgeARM** [comment]
@rohit-unnimadhavan is this resolved in v17.12?

**Comment by rohit-unnimadhavan** [comment]
Hi,

I was just about to get back to you regarding this. The issue persists for me.

I have now compiled the latest version of Compute Library (v17.12) using one of your recommended toolchains (gcc-linaro-4.9-2016.02-x86_64_aarch64-linux-gnu - Downloaded from [https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/aarch64-linux-gnu/](https://releases.linaro.org/components/toolchain/binaries/4.9-2016.02/aarch64-linux-gnu/)) and scons utility. I am building it on an Ubuntu 14.04 64-bit machine. The device I am running this on is also a Linux device. 

The scons parameters I use to build the library is as follows.
scons Werror=1 -j8 debug=0 neon=1 opencl=1 os=linux arch=arm64-v8a build=cross_compile

I am building the application as follows:
aarch64-linux-gnu-g++ examples/acl_colorconvert_1.cpp utils/Utils.cpp -I. -Iinclude -std=c++11 -L. -Lbuild -Lbuild/opencl-1.2-stubs -larm_compute -larm_compute_core -lOpenCL -o acl_colorConvert -DARM_COMPUTE_CL

Now, with this also I am able to see the reported issue. The code (acl_colorconvert_1.txt) and log (acl_colorConvert_log.txt) are attached here for recreating the issue at your end.

[acl_colorconvert_1.txt](https://github.com/ARM-software/ComputeLibrary/files/1645635/acl_colorconvert_1.txt)
[acl_colorConvert_log.txt](https://github.com/ARM-software/ComputeLibrary/files/1645636/acl_colorConvert_log.txt)

Please let me know how this can be resolved.

Thanks,
Rohit

**Comment by mdigiorgio** [comment]
Hi Rohit,

I've tested your code on v17.12 on multiple 64-bit Linux platforms and I was not able to reproduce the issue. In fact, I do not see any mismatches between NEON and CL outputs.

Also, it's not clear to me how you can test cases 2), 3) and 4) given that both NEON and CL ColorConvert kernels do not support those conversions. How do you run those?

Another question would be, what version of the OpenCL library are you using?

**Comment by manjunathahg** [comment]
Hi @mdigiorgio 
Thank you for the response.
According to the available documentation, [void configure(const IImage * input, IMultiImage * output) function in NEColorConvert](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_n_e_color_convert.xhtml#a70de58654d68781741900307d970912a)      supports RGB888/RGBA8888 => YUV444  on neon (cases 2 and 3).
Similarly [void configure(const ICLImage *input, ICLMultiImage *      output) in CLColorConvert](https://arm-software.github.io/ComputeLibrary/latest/classarm__compute_1_1_c_l_color_convert.xhtml#a0240dc06ada517594f39f25d5228b9c7) supports RGBA8888 => YUV444 conversion (case 4). 
We will get back with the OpenCL version.

**Comment by manjunathahg** [comment]
Hi @mdigiorgio the OpenCL version we are using is 1.2

**Comment by mdigiorgio** [comment]
Hi @manjunathahg,

Thanks for the information. Two points:
- in the code you have provided, you are using format UYVY422, not YUV444.
- The configure methods you mentioned are not the ones that get called in your examples. In fact, in the example you declare srcImage and dstImage as Image / CLImage objects, whereas the ones you mentioned are called when you use an IMultiImage / ICLMultiImage object as destination. This makes sense because you want a conversion to a planar format, so the output should be a multi planar image.

Hope this helps.

**Comment by mpekatsoula** [comment]
Closing, reopen if needed
