### ISSUE TITLE
 tensorflow_data_extractor.py error  tensorflow 1.4.0

### ISSUE THREAD

**Issue by hexiangquan** [ARM-software/ComputeLibrary#324]
python  tensorflow_data_extractor.py   -m  ../cnn_data/mobilenet_v1_0.25_128_2017_06_14/mobilenet_v1_0.25_128.ckpt   -n ../cnn_data/mobilenet_v1_0.25_128_2017_06_14/mobilenet_v1_0.25_128.ckpt.meta
Traceback (most recent call last):
  File "tensorflow_data_extractor.py", line 38, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1810, in import_meta_graph
    **kwargs)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named SSTableReaderV2 in defined operations

**Comment by AnthonyARM** [comment]
Looks more like TensorFlow fails to load your network than a problem with the script, no ?

**Comment by GeorgeARM** [comment]
Hello @hexiangquan ,

According to [this](https://github.com/tensorflow/models/issues/1564) problem should have been solved in tensorflow 1.4. We will have a look as well but as @AnthonyARM mentioned this doesn't seem to be an issue with the script itself.

**Comment by hexiangquan** [comment]
but i have upgraded it to 1.4.1 .still encounter  the some problem. my env  tensorflow 1.4.1+py2.7 .try to extract npy from ssd_mobilenet v1 


发自我的 iPhone

**Comment by kaishijeng** [comment]
My error below is different. My tensorflow is r1.5

python ./scripts/tensorflow_data_extractor.py  -m tf_models/model.ckpt-1870760.data-00000-of-00001 -n tf_models/model.ckpt-1870760.meta
Traceback (most recent call last):
  File "./scripts/tensorflow_data_extractor.py", line 41, in <module>
    saver.restore(sess, args.modelFile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1686, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot assign a device for operation 'gradients/Loss/Loss_1/sub_grad/BroadcastGradientArgs': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: gradients/Loss/Loss_1/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/device:GPU:0"](gradients/Loss/Loss_1/sub_grad/Shape, gradients/Loss/Loss_1/sub_grad/Shape_1)]]

Caused by op u'gradients/Loss/Loss_1/sub_grad/BroadcastGradientArgs', defined at:
  File "./scripts/tensorflow_data_extractor.py", line 38, in <module>
    saver = tf.train.import_meta_graph(args.netFile)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1838, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 660, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/deprecation.py", line 316, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 554, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Cannot assign a device for operation 'gradients/Loss/Loss_1/sub_grad/BroadcastGradientArgs': Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0 ]. Make sure the device specification refers to a valid device.
         [[Node: gradients/Loss/Loss_1/sub_grad/BroadcastGradientArgs = BroadcastGradientArgs[T=DT_INT32, _device="/device:GPU:0"](gradients/Loss/Loss_1/sub_grad/Shape, gradients/Loss/Loss_1/sub_grad/Shape_1)]]

**Comment by hexiangquan** [comment]
@AnthonyARM maybe my model is different from yours  .can you share model'S URL with me  mobilenetSSD

**Comment by kaishijeng** [comment]
@AnthonyARM 

  Any update on this issue?

Thanks,

**Comment by GeorgeARM** [comment]
Hello,

We use the model from the slim models [here](https://github.com/tensorflow/models/tree/master/research/slim).
Unfortunately, we had the same issue you had and we followed the steps in tensorflow github issue that I mentioned above, and then dumped the values manually.
We will look into our script and update it in case the way of loading models in tf has changed.

**Comment by hexiangquan** [comment]
@GeorgeARM thank you .look forward update.

**Comment by GeorgeARM** [comment]
@hexiangquan ,

We had a look at this and its not a problem in our script. The models that you are trying to load were dumped using operations that are not part of the open source tensorflow.
Unfortunately, you will have to follow the comments of the respective tensorflow issue that I mentioned in the [comment](https://github.com/ARM-software/ComputeLibrary/issues/324#issuecomment-354754614) above to dump the trainable parameters.

**Comment by hexiangquan** [comment]
@GeorgeARM  thank you for your help  !  i will test using opensource TF Model

**Comment by zhaofenqiang** [comment]
@hexiangquan  hi, got the same problem, have you solved it ?

**Comment by hexiangquan** [comment]
tensorflow的 ob api有内部接口 自己重新做吧


发自我的 iPhone
